version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - APP_MODE=${APP_MODE}
      - PORT=${PORT:-3000}
      - TBANK_USE_SANDBOX=${TBANK_USE_SANDBOX:-false}
    env_file:
      - .env
    restart: unless-stopped
